//$file${../::decision_ao.h} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
//
// Model: model.qm
// File:  ${../::decision_ao.h}
//
// This code has been generated by QM 7.0.3 <www.state-machine.com/qm>.
// DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
//
// Copyright (c) 2005 Quantum Leaps, LLC. All rights reserved.
//
//                 ____________________________________
//                /                                   /
//               /    GGGGGGG    PPPPPPPP   LL       /
//              /   GG     GG   PP     PP  LL       /
//             /   GG          PP     PP  LL       /
//            /   GG   GGGGG  PPPPPPPP   LL       /
//           /   GG      GG  PP         LL       /
//          /     GGGGGGG   PP         LLLLLLL  /
//         /___________________________________/
//
// SPDX-License-Identifier: GPL-3.0-or-later
//
// This generated code is open-source software licensed under the GNU
// General Public License (GPL) as published by the Free Software Foundation
// (see <https://www.gnu.org/licenses>).
//
// NOTE:
// The GPL does NOT permit the incorporation of this code into proprietary
// programs. Please contact Quantum Leaps for commercial licensing options,
// which expressly supersede the GPL and are designed explicitly for
// closed-source distribution.
//
// Quantum Leaps contact information:
// <www.state-machine.com/licensing>
// <info@state-machine.com>
//
//$endhead${../::decision_ao.h} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#ifndef DECISION_AO_H_
#define DECISION_AO_H_

#include "qpc.h"

//$declare${HeroUp::DecisionAO} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${HeroUp::DecisionAO} ......................................................
typedef struct DecisionAO {
// protected:
    QActive super;

// public:
    uint8_t ctrl_terminal;
    uint8_t fric_mode;
    uint8_t sniper;
    uint8_t mouse_fix;
    uint8_t world_enable;
    uint8_t cam_target;

// private:
    uint8_t rc_lost_flag;

// public:
    uint8_t can_enable;
} DecisionAO;

extern DecisionAO DecisionAO_inst;

// protected:
QState DecisionAO_initial(DecisionAO * const me, void const * const par);
QState DecisionAO_Protected(DecisionAO * const me, QEvt const * const e);
QState DecisionAO_NormalMode(DecisionAO * const me, QEvt const * const e);
QState DecisionAO_SniperMode(DecisionAO * const me, QEvt const * const e);
QState DecisionAO_WorldGimbal(DecisionAO * const me, QEvt const * const e);
//$enddecl${HeroUp::DecisionAO} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$declare${HeroUpShared} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${HeroUpShared::StateMachineSig} ...........................................
enum StateMachineSig {
    SwitchR_up_SIG=Q_USER_SIG,
    SwitchR_mid_SIG,
    SwitchR_down_SIG,
    SwitchL_up_SIG,
    SwitchL_mid_SIG,
    SwitchL_down_SIG,
    Switch_protected_SIG,
    Switch_PC_SIG,
    Switch_RC_SIG,
    RC_LOST_SIG,

    SWITCH_SNIPER_SIG,
    SWITCH_WORLD_SIG,

    SWITCH_FRIC_SIG,

    SWITCH_MOUSE_FIX_SIG,
    NEXT_CAM_TARGET_SIG,

    MAX_PUB_SIG,
    TIMEOUT_SIG,
};

//${HeroUpShared::CtrlTerminalEnum} ..........................................
enum CtrlTerminalEnum {
    CONTROL_STOP = 0, CONTROL_FROM_REMOTE, CONTROL_FROM_PC
};

//${HeroUpShared::FricModeEnum} ..............................................
enum FricModeEnum { FRIC_OFF = 0, FRIC_ON };

//${HeroUpShared::SniperModeEnum} ............................................
enum SniperModeEnum { SNIPER_OFF = 0, SNIPER_ON };

//${HeroUpShared::MouseFixModeEnum} ..........................................
enum MouseFixModeEnum { MOUSE_FIX_OFF = 0, MOUSE_FIX_ON };

//${HeroUpShared::WorldModeEnum} .............................................
enum WorldModeEnum { WORLD_ENABLE_OFF = 0, WORLD_ENABLE_ON };

//${HeroUpShared::CamTargetEnum} .............................................
enum CamTargetEnum {
    CAM_TARGET_UP = 1, CAM_TARGET_MID, CAM_TARGET_DOWN
};

//${HeroUpShared::DecisionAO_ctor} ...........................................
void DecisionAO_ctor(void);

//${HeroUpShared::AO_DecisionAO} .............................................
extern QActive * const AO_DecisionAO;

//${HeroUpShared::pDecisionAO} ...............................................
extern const DecisionAO * pDecisionAO;

//${HeroUpShared::CanEnableEnum} .............................................
enum CanEnableEnum { CAN_DISABLE = 0, CAN_ENABLE };
//$enddecl${HeroUpShared} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^


#endif
