//$file${../::decision_ao.c} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
//
// Model: model.qm
// File:  ${../::decision_ao.c}
//
// This code has been generated by QM 7.0.3 <www.state-machine.com/qm>.
// DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
//
// Copyright (c) 2005 Quantum Leaps, LLC. All rights reserved.
//
//                 ____________________________________
//                /                                   /
//               /    GGGGGGG    PPPPPPPP   LL       /
//              /   GG     GG   PP     PP  LL       /
//             /   GG          PP     PP  LL       /
//            /   GG   GGGGG  PPPPPPPP   LL       /
//           /   GG      GG  PP         LL       /
//          /     GGGGGGG   PP         LLLLLLL  /
//         /___________________________________/
//
// SPDX-License-Identifier: GPL-3.0-or-later
//
// This generated code is open-source software licensed under the GNU
// General Public License (GPL) as published by the Free Software Foundation
// (see <https://www.gnu.org/licenses>).
//
// NOTE:
// The GPL does NOT permit the incorporation of this code into proprietary
// programs. Please contact Quantum Leaps for commercial licensing options,
// which expressly supersede the GPL and are designed explicitly for
// closed-source distribution.
//
// Quantum Leaps contact information:
// <www.state-machine.com/licensing>
// <info@state-machine.com>
//
//$endhead${../::decision_ao.c} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#include "decision_ao.h"
#include "general_task_include.h"

//$skip${QP_VERSION} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
// Check for the minimum required QP version
#if (QP_VERSION < 800U) || (QP_VERSION != ((QP_RELEASE^4294967295U)%0x2710U))
#error qpc version 8.0.0 or higher required
#endif
//$endskip${QP_VERSION} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$define${HeroUpShared} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${HeroUpShared::DecisionAO_ctor} ...........................................
void DecisionAO_ctor(void) {
    DecisionAO * const me = &DecisionAO_inst;

    QActive_ctor(&me->super, Q_STATE_CAST(&DecisionAO_initial));

    me->ctrl_terminal = CONTROL_STOP;
    me->fric_mode = FRIC_OFF;
    me->sniper = SNIPER_OFF;
    me->mouse_fix = MOUSE_FIX_OFF;
    me->world_enable = WORLD_ENABLE_OFF;
    me->cam_target = CAM_TARGET_MID;
    me->can_enable = CAN_DISABLE;
}

//${HeroUpShared::AO_DecisionAO} .............................................
QActive * const AO_DecisionAO = &DecisionAO_inst.super;

//${HeroUpShared::pDecisionAO} ...............................................
const DecisionAO * pDecisionAO = &DecisionAO_inst;
//$enddef${HeroUpShared} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$define${HeroUp::DecisionAO} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${HeroUp::DecisionAO} ......................................................
DecisionAO DecisionAO_inst;

//${HeroUp::DecisionAO::SM} ..................................................
QState DecisionAO_initial(DecisionAO * const me, void const * const par) {
    //${HeroUp::DecisionAO::SM::initial}
    return Q_TRAN(&DecisionAO_Protected);
}

//${HeroUp::DecisionAO::SM::Protected} .......................................
QState DecisionAO_Protected(DecisionAO * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${HeroUp::DecisionAO::SM::Protected}
        case Q_ENTRY_SIG: {
            me->ctrl_terminal = CONTROL_STOP;
            me->fric_mode = FRIC_OFF;
            me->sniper = SNIPER_OFF;
            me->mouse_fix = MOUSE_FIX_OFF;
            me->world_enable = WORLD_ENABLE_OFF;
            me->cam_target = CAM_TARGET_MID;
            me->can_enable = CAN_DISABLE;
            status_ = Q_HANDLED();
            break;
        }
        //${HeroUp::DecisionAO::SM::Protected::RC_LOST}
        case RC_LOST_SIG: {
            status_ = Q_TRAN(&DecisionAO_Protected);
            break;
        }
        //${HeroUp::DecisionAO::SM::Protected::Switch_PC}
        case Switch_PC_SIG: {
            me->ctrl_terminal = CONTROL_FROM_PC;
            status_ = Q_TRAN(&DecisionAO_NormalMode);
            break;
        }
        //${HeroUp::DecisionAO::SM::Protected::Switch_RC}
        case Switch_RC_SIG: {
            me->ctrl_terminal = CONTROL_FROM_REMOTE;
            status_ = Q_TRAN(&DecisionAO_NormalMode);
            break;
        }
        //${HeroUp::DecisionAO::SM::Protected::Switch_protected}
        case Switch_protected_SIG: {
            status_ = Q_HANDLED();
            break;
        }
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}

//${HeroUp::DecisionAO::SM::NormalMode} ......................................
QState DecisionAO_NormalMode(DecisionAO * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${HeroUp::DecisionAO::SM::NormalMode}
        case Q_ENTRY_SIG: {
            me->fric_mode = FRIC_OFF;
            me->sniper = SNIPER_OFF;
            me->mouse_fix = MOUSE_FIX_OFF;
            me->world_enable = WORLD_ENABLE_OFF;
            me->cam_target = CAM_TARGET_MID;
            me->can_enable = CAN_ENABLE;
            status_ = Q_HANDLED();
            break;
        }
        //${HeroUp::DecisionAO::SM::NormalMode::SWITCH_SNIPER}
        case SWITCH_SNIPER_SIG: {
            status_ = Q_TRAN(&DecisionAO_SniperMode);
            break;
        }
        //${HeroUp::DecisionAO::SM::NormalMode::Switch_RC}
        case Switch_RC_SIG: {
            me->ctrl_terminal = CONTROL_FROM_REMOTE;
            status_ = Q_HANDLED();
            break;
        }
        //${HeroUp::DecisionAO::SM::NormalMode::Switch_PC}
        case Switch_PC_SIG: {
            me->ctrl_terminal = CONTROL_FROM_PC;
            status_ = Q_HANDLED();
            break;
        }
        //${HeroUp::DecisionAO::SM::NormalMode::Switch_protected}
        case Switch_protected_SIG: {
            status_ = Q_TRAN(&DecisionAO_Protected);
            break;
        }
        //${HeroUp::DecisionAO::SM::NormalMode::RC_LOST}
        case RC_LOST_SIG: {
            status_ = Q_TRAN(&DecisionAO_Protected);
            break;
        }
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}

//${HeroUp::DecisionAO::SM::NormalMode::SniperMode} ..........................
QState DecisionAO_SniperMode(DecisionAO * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${HeroUp::DecisionAO::SM::NormalMode::SniperMode}
        case Q_ENTRY_SIG: {
            me->world_enable = WORLD_ENABLE_OFF;
            me->sniper = SNIPER_ON;
            status_ = Q_HANDLED();
            break;
        }
        //${HeroUp::DecisionAO::SM::NormalMode::SniperMode::SWITCH_WORLD}
        case SWITCH_WORLD_SIG: {
            status_ = Q_TRAN(&DecisionAO_WorldGimbal);
            break;
        }
        //${HeroUp::DecisionAO::SM::NormalMode::SniperMode::SWITCH_SNIPER}
        case SWITCH_SNIPER_SIG: {
            status_ = Q_TRAN(&DecisionAO_NormalMode);
            break;
        }
        default: {
            status_ = Q_SUPER(&DecisionAO_NormalMode);
            break;
        }
    }
    return status_;
}

//${HeroUp::DecisionAO::SM::NormalMode::SniperMode::WorldGimbal} .............
QState DecisionAO_WorldGimbal(DecisionAO * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${HeroUp::DecisionAO::SM::NormalMode::SniperMode::WorldGimbal}
        case Q_ENTRY_SIG: {
            me->world_enable = WORLD_ENABLE_ON;
            status_ = Q_HANDLED();
            break;
        }
        //${HeroUp::DecisionAO::SM::NormalMode::SniperMode::WorldGimbal::SWITCH_WORLD}
        case SWITCH_WORLD_SIG: {
            status_ = Q_TRAN(&DecisionAO_SniperMode);
            break;
        }
        default: {
            status_ = Q_SUPER(&DecisionAO_SniperMode);
            break;
        }
    }
    return status_;
}
//$enddef${HeroUp::DecisionAO} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
