//$file${../::decision_ao.h} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
//
// Model: decision_ao.qm
// File:  ${../::decision_ao.h}
//
// This code has been generated by QM 7.0.3 <www.state-machine.com/qm>.
// DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
//
// Copyright (c) 2005 Quantum Leaps, LLC. All rights reserved.
//
//                 ____________________________________
//                /                                   /
//               /    GGGGGGG    PPPPPPPP   LL       /
//              /   GG     GG   PP     PP  LL       /
//             /   GG          PP     PP  LL       /
//            /   GG   GGGGG  PPPPPPPP   LL       /
//           /   GG      GG  PP         LL       /
//          /     GGGGGGG   PP         LLLLLLL  /
//         /___________________________________/
//
// SPDX-License-Identifier: GPL-3.0-or-later
//
// This generated code is open-source software licensed under the GNU
// General Public License (GPL) as published by the Free Software Foundation
// (see <https://www.gnu.org/licenses>).
//
// NOTE:
// The GPL does NOT permit the incorporation of this code into proprietary
// programs. Please contact Quantum Leaps for commercial licensing options,
// which expressly supersede the GPL and are designed explicitly for
// closed-source distribution.
//
// Quantum Leaps contact information:
// <www.state-machine.com/licensing>
// <info@state-machine.com>
//
//$endhead${../::decision_ao.h} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#ifndef DECISION_AO_H_
#define DECISION_AO_H_

#include "qpc.h"

//$declare${Hero_Demo::DecisionAO} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${Hero_Demo::DecisionAO} ...................................................
typedef struct DecisionAO {
// protected:
    QActive super;

// public:
    uint8_t ctrl_terminal;
    uint8_t chassis_mode;
    uint8_t sniper;
    uint8_t fric_mode;
    uint8_t stir_mode;
    uint8_t joint_mode;
    uint8_t stand_mode;
    uint8_t mouse_fix;
    uint8_t cam_target;
    uint8_t world_enable;
    uint8_t stable;

// private:
    QTimeEvt timeEvt_test;
    uint8_t rc_lost_flag;

// public:
    uint8_t can_enable;
} DecisionAO;

extern DecisionAO DecisionAO_inst;

// public:
void DecisionAO_State_Stable(DecisionAO * const me);
void DecisionAO_Stable_Unstable(DecisionAO * const me);
uint8_t DecisionAO_is_Stable(DecisionAO * const me);

// protected:
QState DecisionAO_initial(DecisionAO * const me, void const * const par);
QState DecisionAO_Protected(DecisionAO * const me, QEvt const * const e);
QState DecisionAO_NormalMode(DecisionAO * const me, QEvt const * const e);
QState DecisionAO_SniperMode(DecisionAO * const me, QEvt const * const e);
QState DecisionAO_WorldGimbal(DecisionAO * const me, QEvt const * const e);
QState DecisionAO_Stand_High(DecisionAO * const me, QEvt const * const e);
QState DecisionAO_Revolve(DecisionAO * const me, QEvt const * const e);
QState DecisionAO_FollowBck(DecisionAO * const me, QEvt const * const e);
QState DecisionAO_PreStair(DecisionAO * const me, QEvt const * const e);
QState DecisionAO_StairUp(DecisionAO * const me, QEvt const * const e);
//$enddecl${Hero_Demo::DecisionAO} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

//$declare${Hero_Shared} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${Hero_Shared::StateMachineSig} ............................................
enum StateMachineSig {
    SwitchR_up_SIG=Q_USER_SIG,
    SwitchR_mid_SIG,
    SwitchR_down_SIG,
    SwitchL_up_SIG,
    SwitchL_mid_SIG,
    SwitchL_down_SIG,
    Switch_protected_SIG,
    Switch_PC_SIG,
    Switch_RC_SIG,
    RC_LOST_SIG,
    SWITCH_SNIPER_SIG,
    SWITCH_BACK_SIG,
    SWITCH_STAND_SIG,
    SWITCH_REVOLVE_SIG,
    SWITCH_WORLD_SIG,
    STAIR_OK_SIG,
    MAX_PUB_SIG,
    TIMEOUT_SIG,
    SWITCH_STAIR_SIG,
    SWITCH_FINAL_SIG,
};

//${Hero_Shared::CtrlTerminalEnum} ...........................................
enum CtrlTerminalEnum { CTRL_STOP = 0, CTRL_REMOTE, CTRL_PC };

//${Hero_Shared::ChassisModeEnum} ............................................
enum ChassisModeEnum  { CHS_FOLLOW = 0, CHS_FOLLOW_BACK, CHS_REVOLVE };

//${Hero_Shared::DecisionAO_ctor} ............................................
void DecisionAO_ctor(void);

//${Hero_Shared::AO_DecisionAO} ..............................................
extern QActive * const AO_DecisionAO;

//${Hero_Shared::pDecisionAO} ................................................
extern const DecisionAO * pDecisionAO;
//$enddecl${Hero_Shared} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

#endif

