//$file${../::decision_ao.c} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
//
// Model: decision_ao.qm
// File:  ${../::decision_ao.c}
//
// This code has been generated by QM 7.0.3 <www.state-machine.com/qm>.
// DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
//
// Copyright (c) 2005 Quantum Leaps, LLC. All rights reserved.
//
//                 ____________________________________
//                /                                   /
//               /    GGGGGGG    PPPPPPPP   LL       /
//              /   GG     GG   PP     PP  LL       /
//             /   GG          PP     PP  LL       /
//            /   GG   GGGGG  PPPPPPPP   LL       /
//           /   GG      GG  PP         LL       /
//          /     GGGGGGG   PP         LLLLLLL  /
//         /___________________________________/
//
// SPDX-License-Identifier: GPL-3.0-or-later
//
// This generated code is open-source software licensed under the GNU
// General Public License (GPL) as published by the Free Software Foundation
// (see <https://www.gnu.org/licenses>).
//
// NOTE:
// The GPL does NOT permit the incorporation of this code into proprietary
// programs. Please contact Quantum Leaps for commercial licensing options,
// which expressly supersede the GPL and are designed explicitly for
// closed-source distribution.
//
// Quantum Leaps contact information:
// <www.state-machine.com/licensing>
// <info@state-machine.com>
//
//$endhead${../::decision_ao.c} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#include "decision_ao.h"
#include "general_task_include.h"

//$skip${QP_VERSION} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
// Check for the minimum required QP version
#if (QP_VERSION < 800U) || (QP_VERSION != ((QP_RELEASE^4294967295U)%0x2710U))
#error qpc version 8.0.0 or higher required
#endif
//$endskip${QP_VERSION} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$define${Hero_Shared} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${Hero_Shared::DecisionAO_ctor} ............................................
void DecisionAO_ctor(void) {
    DecisionAO * const me = &DecisionAO_inst;
    QActive_ctor(&me->super, Q_STATE_CAST(&DecisionAO_initial));
    QTimeEvt_ctorX(&me->timeEvt_test, &me->super, TIMEOUT_SIG, 0U);
    me->ctrl_terminal = CTRL_STOP;
    me->chassis_mode = CHS_FOLLOW;
    me->sniper = SNIPER_OFF;
    me->fric_mode = FRIC_OFF;
    me->stir_mode = STIR_LOCK;
    me->joint_mode = JOINT_NORMAL;
    me->stand_mode = STAND_NORMAL;
    me->mouse_fix = MOUSE_FIX_OFF;
    me->cam_target = CAM_TARGET_MID;
    me->world_enable = WORLD_ENABLE_OFF;
    me->rc_lost_flag = RC_LOST;
    me->can_enable = CAN_DISABLE;
}

//${Hero_Shared::AO_DecisionAO} ..............................................
QActive * const AO_DecisionAO = &DecisionAO_inst.super;

//${Hero_Shared::pDecisionAO} ................................................
const DecisionAO * pDecisionAO = &DecisionAO_inst;
//$enddef${Hero_Shared} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$define${Hero_Demo::DecisionAO} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${Hero_Demo::DecisionAO} ...................................................
DecisionAO DecisionAO_inst;

//${Hero_Demo::DecisionAO::State_Stable} .....................................
void DecisionAO_State_Stable(DecisionAO * const me) {
    me->stable=1;
}

//${Hero_Demo::DecisionAO::Stable_Unstable} ..................................
void DecisionAO_Stable_Unstable(DecisionAO * const me) {
    me->stable=0;
}

//${Hero_Demo::DecisionAO::is_Stable} ........................................
uint8_t DecisionAO_is_Stable(DecisionAO * const me) {
    return me->stable;
}

//${Hero_Demo::DecisionAO::SM} ...............................................
QState DecisionAO_initial(DecisionAO * const me, void const * const par) {
    //${Hero_Demo::DecisionAO::SM::initial}
    return Q_TRAN(&DecisionAO_Protected);
}

//${Hero_Demo::DecisionAO::SM::Protected} ....................................
QState DecisionAO_Protected(DecisionAO * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${Hero_Demo::DecisionAO::SM::Protected}
        case Q_ENTRY_SIG: {
            me->ctrl_terminal = CTRL_STOP;
            me->chassis_mode = CHS_FOLLOW;
            me->sniper = SNIPER_OFF;
            me->fric_mode = FRIC_OFF;
            me->stir_mode = STIR_LOCK;
            me->joint_mode = JOINT_NORMAL;
            me->stand_mode = STAND_NORMAL;
            me->mouse_fix = MOUSE_FIX_OFF;
            me->cam_target = CAM_TARGET_MID;
            me->world_enable = WORLD_ENABLE_OFF;
            me->can_enable = CAN_DISABLE;
            status_ = Q_HANDLED();
            break;
        }
        //${Hero_Demo::DecisionAO::SM::Protected::RC_LOST}
        case RC_LOST_SIG: {
            status_ = Q_TRAN(&DecisionAO_Protected);
            break;
        }
        //${Hero_Demo::DecisionAO::SM::Protected::Switch_RC}
        case Switch_RC_SIG: {
            me->ctrl_terminal = CTRL_REMOTE;
            status_ = Q_TRAN(&DecisionAO_NormalMode);
            break;
        }
        //${Hero_Demo::DecisionAO::SM::Protected::Switch_PC}
        case Switch_PC_SIG: {
            me->ctrl_terminal = CTRL_PC;
            status_ = Q_TRAN(&DecisionAO_NormalMode);
            break;
        }
        //${Hero_Demo::DecisionAO::SM::Protected::SWITCH_FINAL}
        case SWITCH_FINAL_SIG: {
            status_ = Q_HANDLED();
            break;
        }
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}

//${Hero_Demo::DecisionAO::SM::Protected::NormalMode} ........................
QState DecisionAO_NormalMode(DecisionAO * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${Hero_Demo::DecisionAO::SM::Protected::NormalMode}
        case Q_ENTRY_SIG: {
            //switch2Normal
            me->chassis_mode = CHS_FOLLOW;
            me->sniper = SNIPER_OFF;
            me->fric_mode = FRIC_OFF;
            me->stir_mode = STIR_ANGLE_CONTROL;
            me->joint_mode = JOINT_NORMAL;
            me->stand_mode = STAND_NORMAL;
            me->mouse_fix = MOUSE_FIX_OFF;
            me->cam_target = CAM_TARGET_MID;
            me->world_enable = WORLD_ENABLE_OFF;
            me->can_enable = CAN_ENABLE;
            status_ = Q_HANDLED();
            break;
        }
        //${Hero_Demo::DecisionAO::SM::Protected::NormalMode::SWITCH_FINAL}
        case SWITCH_FINAL_SIG: {
            status_ = Q_TRAN(&DecisionAO_Protected);
            break;
        }
        //${Hero_Demo::DecisionAO::SM::Protected::NormalMode::SWITCH_SNIPER}
        case SWITCH_SNIPER_SIG: {
            status_ = Q_TRAN(&DecisionAO_SniperMode);
            break;
        }
        //${Hero_Demo::DecisionAO::SM::Protected::NormalMode::SWITCH_STAND}
        case SWITCH_STAND_SIG: {
            status_ = Q_TRAN(&DecisionAO_Stand_High);
            break;
        }
        //${Hero_Demo::DecisionAO::SM::Protected::NormalMode::SWITCH_REVOLVE}
        case SWITCH_REVOLVE_SIG: {
            status_ = Q_TRAN(&DecisionAO_Revolve);
            break;
        }
        //${Hero_Demo::DecisionAO::SM::Protected::NormalMode::SWITCH_STAIR}
        case SWITCH_STAIR_SIG: {
            status_ = Q_TRAN(&DecisionAO_PreStair);
            break;
        }
        //${Hero_Demo::DecisionAO::SM::Protected::NormalMode::SWITCH_BACK}
        case SWITCH_BACK_SIG: {
            status_ = Q_TRAN(&DecisionAO_FollowBck);
            break;
        }
        //${Hero_Demo::DecisionAO::SM::Protected::NormalMode::Switch_PC}
        case Switch_PC_SIG: {
            me->ctrl_terminal = CTRL_PC;
            status_ = Q_HANDLED();
            break;
        }
        //${Hero_Demo::DecisionAO::SM::Protected::NormalMode::Switch_RC}
        case Switch_RC_SIG: {
            me->ctrl_terminal = CTRL_REMOTE;
            status_ = Q_HANDLED();
            break;
        }
        default: {
            status_ = Q_SUPER(&DecisionAO_Protected);
            break;
        }
    }
    return status_;
}

//${Hero_Demo::DecisionAO::SM::Protected::NormalMode::SniperMode} ............
QState DecisionAO_SniperMode(DecisionAO * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${Hero_Demo::DecisionAO::SM::Protected::NormalMode::SniperMode}
        case Q_ENTRY_SIG: {
            me->sniper = SNIPER_ON;
            status_ = Q_HANDLED();
            break;
        }
        //${Hero_Demo::DecisionAO::SM::Protected::NormalMode::SniperMode}
        case Q_EXIT_SIG: {
            me->sniper = SNIPER_OFF;
            status_ = Q_HANDLED();
            break;
        }
        //${Hero_Demo::DecisionAO::SM::Protected::NormalMode::SniperMode::SwitchR_down}
        case SwitchR_down_SIG: {
            status_ = Q_HANDLED();
            break;
        }
        //${Hero_Demo::DecisionAO::SM::Protected::NormalMode::SniperMode::SWITCH_SNIPER}
        case SWITCH_SNIPER_SIG: {
            status_ = Q_TRAN(&DecisionAO_NormalMode);
            break;
        }
        //${Hero_Demo::DecisionAO::SM::Protected::NormalMode::SniperMode::SWITCH_WORLD}
        case SWITCH_WORLD_SIG: {
            status_ = Q_TRAN(&DecisionAO_WorldGimbal);
            break;
        }
        default: {
            status_ = Q_SUPER(&DecisionAO_NormalMode);
            break;
        }
    }
    return status_;
}

//${Hero_Demo::DecisionAO::SM::Protected::NormalMode::SniperMode::WorldGimbal}
QState DecisionAO_WorldGimbal(DecisionAO * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${Hero_Demo::DecisionAO::SM::Protected::NormalMode::SniperMode::WorldGimbal}
        case Q_ENTRY_SIG: {
            me->world_enable = WORLD_ENABLE_ON;
            status_ = Q_HANDLED();
            break;
        }
        //${Hero_Demo::DecisionAO::SM::Protected::NormalMode::SniperMode::WorldGimbal}
        case Q_EXIT_SIG: {
            me->world_enable = WORLD_ENABLE_OFF;
            status_ = Q_HANDLED();
            break;
        }
        //${Hero_Demo::DecisionAO::SM::Protected::NormalMode::SniperMode::WorldGimbal::SWITCH_WORLD}
        case SWITCH_WORLD_SIG: {
            status_ = Q_TRAN(&DecisionAO_SniperMode);
            break;
        }
        default: {
            status_ = Q_SUPER(&DecisionAO_SniperMode);
            break;
        }
    }
    return status_;
}

//${Hero_Demo::DecisionAO::SM::Protected::NormalMode::PreStair} ..............
QState DecisionAO_PreStair(DecisionAO * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${Hero_Demo::DecisionAO::SM::Protected::NormalMode::PreStair}
        case Q_ENTRY_SIG: {
            me->joint_mode = JOINT_PRESTAIR;
            status_ = Q_HANDLED();
            break;
        }
        //${Hero_Demo::DecisionAO::SM::Protected::NormalMode::PreStair::SWITCH_STAIR}
        case SWITCH_STAIR_SIG: {
            status_ = Q_TRAN(&DecisionAO_NormalMode);
            break;
        }
        //${Hero_Demo::DecisionAO::SM::Protected::NormalMode::PreStair::STAIR_OK}
        case STAIR_OK_SIG: {
            status_ = Q_TRAN(&DecisionAO_StairUp);
            break;
        }
        default: {
            status_ = Q_SUPER(&DecisionAO_NormalMode);
            break;
        }
    }
    return status_;
}

//${Hero_Demo::DecisionAO::SM::Protected::NormalMode::StairUp} ...............
QState DecisionAO_StairUp(DecisionAO * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${Hero_Demo::DecisionAO::SM::Protected::NormalMode::StairUp}
        case Q_ENTRY_SIG: {
            me->joint_mode = JOINT_STAIRUP;
            status_ = Q_HANDLED();
            break;
        }
        //${Hero_Demo::DecisionAO::SM::Protected::NormalMode::StairUp}
        case Q_EXIT_SIG: {
            me->joint_mode = JOINT_NORMAL;
            status_ = Q_HANDLED();
            break;
        }
        //${Hero_Demo::DecisionAO::SM::Protected::NormalMode::StairUp::SWITCH_STAIR}
        case SWITCH_STAIR_SIG: {
            status_ = Q_TRAN(&DecisionAO_NormalMode);
            break;
        }
        default: {
            status_ = Q_SUPER(&DecisionAO_NormalMode);
            break;
        }
    }
    return status_;
}

//${Hero_Demo::DecisionAO::SM::Protected::NormalMode::Stand_High} ............
QState DecisionAO_Stand_High(DecisionAO * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${Hero_Demo::DecisionAO::SM::Protected::NormalMode::Stand_High}
        case Q_ENTRY_SIG: {
            me->stand_mode = STAND_HIGH;
            status_ = Q_HANDLED();
            break;
        }
        //${Hero_Demo::DecisionAO::SM::Protected::NormalMode::Stand_High}
        case Q_EXIT_SIG: {
            me->stand_mode = STAND_NORMAL;
            status_ = Q_HANDLED();
            break;
        }
        //${Hero_Demo::DecisionAO::SM::Protected::NormalMode::Stand_High::SWITCH_STAND}
        case SWITCH_STAND_SIG: {
            status_ = Q_TRAN(&DecisionAO_NormalMode);
            break;
        }
        default: {
            status_ = Q_SUPER(&DecisionAO_NormalMode);
            break;
        }
    }
    return status_;
}

//${Hero_Demo::DecisionAO::SM::Protected::NormalMode::Revolve} ...............
QState DecisionAO_Revolve(DecisionAO * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${Hero_Demo::DecisionAO::SM::Protected::NormalMode::Revolve}
        case Q_ENTRY_SIG: {
            me->chassis_mode = CHS_REVOLVE;
            status_ = Q_HANDLED();
            break;
        }
        //${Hero_Demo::DecisionAO::SM::Protected::NormalMode::Revolve}
        case Q_EXIT_SIG: {
            me->chassis_mode = CHS_FOLLOW;
            status_ = Q_HANDLED();
            break;
        }
        //${Hero_Demo::DecisionAO::SM::Protected::NormalMode::Revolve::SWITCH_REVOLVE}
        case SWITCH_REVOLVE_SIG: {
            status_ = Q_TRAN(&DecisionAO_NormalMode);
            break;
        }
        default: {
            status_ = Q_SUPER(&DecisionAO_NormalMode);
            break;
        }
    }
    return status_;
}

//${Hero_Demo::DecisionAO::SM::Protected::NormalMode::FollowBck} .............
QState DecisionAO_FollowBck(DecisionAO * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${Hero_Demo::DecisionAO::SM::Protected::NormalMode::FollowBck}
        case Q_ENTRY_SIG: {
            me->chassis_mode = CHS_FOLLOW_BACK;
            status_ = Q_HANDLED();
            break;
        }
        //${Hero_Demo::DecisionAO::SM::Protected::NormalMode::FollowBck}
        case Q_EXIT_SIG: {
            me->chassis_mode = CHS_FOLLOW;
            status_ = Q_HANDLED();
            break;
        }
        //${Hero_Demo::DecisionAO::SM::Protected::NormalMode::FollowBck::SWITCH_BACK}
        case SWITCH_BACK_SIG: {
            status_ = Q_TRAN(&DecisionAO_NormalMode);
            break;
        }
        default: {
            status_ = Q_SUPER(&DecisionAO_NormalMode);
            break;
        }
    }
    return status_;
}
//$enddef${Hero_Demo::DecisionAO} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
